### ISSUE TITLE
Request: (NOT PRIORITY): Validated channels for high viewership people.

### ISSUE THREAD

**Issue by bohl3r** [ExuDev/ExuPro#5]
My thought it to add a validated channels system for famous people so if ExuPro is loaded it will tell that this is the official channel and not a fake. Seeing that their are trademark names taken on Beam... their are sure to be names of high viewership people to be taken. Their is no currently a issue with names being taken on Beam, although it would help users find the correct channel and not let people who are fakes gain followers.

Once again as before... here is my code in HTML:
```html
<div data-role="ExuValidationMessage" class="message">
    <div class="message-body">
        <b>Official Channel for FamousPerson</b>
        <br>Validated to be the offical account of FamousPerson
    </div>
</div> 
```
Then CSS style...
```css
.chat-panel .message[data-role="ExuValidationMessage"] {
    text-align: center;
    border-left: 3px solid #F000FF;
    border-right: 3px solid #F000FF;
}
```
Finally a preview of how it looks:
![Validated Channel Preview](http://imgwiz.com/images/2015/02/22/NV3zy.png)
